--- #YAML:1.0
name:               HTTP-Soup
version:            0.01
abstract:           HTTP client/server library for GNOME
author:
    - Emmanuel Rodriguez <potyl@cpan.org>
license:            perl, lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib:                 1.000
    Glib::Object::Introspection:  0
resources:
    bucktracker:  https://github.com/potyl/perl-HTTP-Soup/issues
    homepage:     https://github.com/potyl/perl-HTTP-Soup
    repository:   https://github.com/potyl/perl-HTTP-Soup
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
